version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
    - /data/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=r00t
    - MYSQL_USER=root
    - MYSQL_DATABASE=employee
    - MYSQL_PASSWORD=r00t
    restart: always
    ports:
    - "3306:3306"
  api:
    container_name: app_employee
    build: .
    ports:
    - "8080:8080"
    environment:
    - WAIT_HOSTS=db:3306
    restart: always
    depends_on:
    - db